### ISSUE TITLE
Unable to create database schema

### ISSUE THREAD

**Issue by falkgotschalk** [olegkrivtsov/using-zf3-book-samples#11]
Hello,
IU have a problem with this step:
//cut
Run database migrations to intialize database schema:

```
./vendor/bin/doctrine-module migrations:migrate
```
//cut

I asume to run this in the terminal (which is nowhere described), I start the command from the directory containing the downloaded files.

I get this error-message:

//cut
Falk-Gottschalks-iMac-neu:userdemo falkgottschalk$ ./vendor/bin/doctrine-module migrations:migrate
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'userdemo', 'golf', Array)
#1 /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(41): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'userdemo', 'golf', Array)
#2 /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'userdemo', 'golf', Array)
#3 /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect()
#4 /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\C in /Applications/MAMP/htdocs/zend/userdemo/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 754

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Applications/MAMP/htdocs/zend/userdemo/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 754

Zend\ServiceManager\Exception\ServiceNotCreatedException: Service with name "doctrine.connection.orm_default" could not be created. Reason: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /Applications/MAMP/htdocs/zend/userdemo/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 754

Call Stack:
    0.0002     351328   1. {main}() /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/doctrine-module/bin/doctrine-module:0
    0.0004     362520   2. include('/Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/doctrine-module/bin/doctrine-module.php') /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/doctrine-module/bin/doctrine-module:4
    0.0773    4557856   3. Zend\ServiceManager\ServiceManager->get() /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/doctrine-module/bin/doctrine-module.php:61
    0.0773    4557856   4. Zend\ServiceManager\ServiceManager->doCreate() /Applications/MAMP/htdocs/zend/userdemo/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:195

//cut

Why you not include a sql-export of the empty databasae? It would be so easy to run in phpmyadmin.

The database itself is running and can be used with several different projects.

I use Mac OS 10.11.6 and MAMP Pro.

**Comment by falkgotschalk** [comment]
Info: One error has been a typing-error in the db-config-file, sorry.
BUT:
the problem is still not solved, the shell dies with the follwing error:

//cut
Falk-Gottschalks-iMac-neu:userdemo falkgottschalk$ ./vendor/bin/doctrine-module migrations:migrate
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'golf', 'golf', Array)
#1 /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(41): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'golf', 'golf', Array)
#2 /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'golf', 'golf', Array)
#3 /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect()
#4 /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->g in /Applications/MAMP/htdocs/zend/userdemo/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 765

**Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Applications/MAMP/htdocs/zend/userdemo/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 765**

Zend\ServiceManager\Exception\ServiceNotCreatedException: Service with name "doctrine.migrations_configuration.orm_default" could not be created. Reason: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /Applications/MAMP/htdocs/zend/userdemo/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 765

Call Stack:
    0.0002     351328   1. {main}() /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/doctrine-module/bin/doctrine-module:0
    0.0006     362520   2. include('/Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/doctrine-module/bin/doctrine-module.php') /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/doctrine-module/bin/doctrine-module:4
    0.6681    4589088   3. Zend\ServiceManager\ServiceManager->get() /Applications/MAMP/htdocs/zend/userdemo/vendor/doctrine/doctrine-module/bin/doctrine-module.php:61
    0.6681    4589088   4. Zend\ServiceManager\ServiceManager->doCreate() /Applications/MAMP/htdocs/zend/userdemo/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:200

Falk-Gottschalks-iMac-neu:userdemo falkgottschalk$ 
//cut

HELP!

**Comment by falkgotschalk** [comment]
Found some coding in the example and created the used table / rows manually.
For the next one who has the same problem:

//cut```

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `email` varchar(128) NOT NULL,
  `full_name` varchar(512) NOT NULL,
  `password` varchar(256) NOT NULL,
  `status` int(11) NOT NULL,
  `date_created` datetime NOT NULL,
  `pwd_reset_token` varchar(32) DEFAULT NULL,
  `pwd_reset_token_creation_date` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
//cut

The sample-entr will be crated automatically by the application.
